// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package db

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type ComplaintAllocations struct {
	ID          uuid.UUID `json:"id"`
	ComplaintID uuid.UUID `json:"complaint_id"`
	AllocatedTo uuid.UUID `json:"allocated_to"`
	AllocatedBy uuid.UUID `json:"allocated_by"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type ComplaintHistory struct {
	ID                uuid.UUID       `json:"id"`
	Complaint         json.RawMessage `json:"complaint"`
	ComplaintInfo     json.RawMessage `json:"complaint_info"`
	ComplaintAllocate json.RawMessage `json:"complaint_allocate"`
	DeviceImages      json.RawMessage `json:"device_images"`
	ComplaintProgress json.RawMessage `json:"complaint_progress"`
	CreatedAt         time.Time       `json:"created_at"`
	UpdatedAt         time.Time       `json:"updated_at"`
}

type ComplaintInfo struct {
	ID                      uuid.UUID      `json:"id"`
	ComplaintID             uuid.UUID      `json:"complaint_id"`
	DeviceID                string         `json:"device_id"`
	ProblemStatement        string         `json:"problem_statement"`
	ProblemCategory         sql.NullString `json:"problem_category"`
	ClientAvailable         time.Time      `json:"client_available"`
	Status                  string         `json:"status"`
	CreatedAt               time.Time      `json:"created_at"`
	UpdatedAt               time.Time      `json:"updated_at"`
	DeviceType              sql.NullString `json:"device_type"`
	DeviceModel             sql.NullString `json:"device_model"`
	ClientAvailableDate     sql.NullTime   `json:"client_available_date"`
	ClientAvailableTimeSlot sql.NullString `json:"client_available_time_slot"`
	ComplaintAddress        sql.NullString `json:"complaint_address"`
}

type ComplaintProgress struct {
	ID                uuid.UUID `json:"id"`
	ComplaintID       uuid.UUID `json:"complaint_id"`
	ProgressStatement string    `json:"progress_statement"`
	StatementBy       uuid.UUID `json:"statement_by"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
}

type Complaints struct {
	ID        uuid.UUID `json:"id"`
	ClientID  string    `json:"client_id"`
	CreatedBy uuid.UUID `json:"created_by"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type DeviceImages struct {
	ID              uuid.UUID      `json:"id"`
	ComplaintInfoID uuid.UUID      `json:"complaint_info_id"`
	DeviceImage     string         `json:"device_image"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	FileType        sql.NullString `json:"file_type"`
}
