// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Complaint struct {
	ID               uuid.UUID      `json:"id"`
	ClientID         uuid.UUID      `json:"client_id"`
	DeviceID         uuid.UUID      `json:"device_id"`
	ProblemStatement string         `json:"problem_statement"`
	ProblemCategory  sql.NullString `json:"problem_category"`
	ClientAvailable  time.Time      `json:"client_available"`
	Status           string         `json:"status"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
}
